/*model */
exports.UnidadOrganizativa = {
    vcIdSede: undefined,
    vcDescripcion: undefined,
    iIdEstado: undefined,
    nvDireccion: undefined,
    iIdUnidadOrganizativa: undefined,
    vcCodigoUbigeo: undefined,
    dtCreacion: undefined,
    dtModificacion: undefined,
    vcUsuarioCreacionApp: undefined,
    vcUsuarioCreacionDB: undefined,
    vcUsuarioCreacionSP: undefined,
    vcUsuarioCreacionOT: undefined,
    vcUsuarioModificacionApp: undefined,
    vcUsuarioModificacionDB: undefined,
    vcUsuarioModificacionSP: undefined,
    vcUsuarioModificacionOT: undefined,
    iIdPrioridad: undefined,
}