exports.Asistencia = {
    iIdAsistencia: undefined,
    vcIdSede: undefined,
    iIdTrabajadorInterno: undefined,
    vcFechaCalendario: undefined,
    vcIdMotivoTareo: undefined,
    iIdEstadoAsistencia: undefined,
    iIdEstadoTareo: undefined,
    tAsistencia: undefined,
    iMinTardanza: undefined,
    nvObservacion: undefined,
    iIdEstado: undefined,
    dtCreacion: undefined,
    dtModificacion: undefined,
    vcUsuarioCreacionApp: undefined,
    vcUsuarioCreacionDB: undefined,
    vcUsuarioCreacionSP: undefined,
    vcUsuarioCreacionOT: undefined,
    vcUsuarioModificacionApp: undefined,
    vcUsuarioModificacionDB: undefined,
    vcUsuarioModificacionSP: undefined,
    vcUsuarioModificacionOT: undefined,
    iIdTareo: undefined,
}