
exports.Movimiento = {
	iIdMovimiento: undefined,
	vcNumeroDocumento: undefined,
	iIdRequerimiento: undefined,
	iItemRQ: undefined,
	dAprobacion: undefined,
	vcIdSede: undefined,
	iIdSistemaTrabajo: undefined,
	iIdPuesto: undefined,
	vcIdAreaNatclar: undefined,
	vbSueldo: undefined,
	vbSueldoDestaque: undefined,
	dCambioSueldo: undefined,
	dInicio: undefined,
	dFin: undefined,
	cPermanente: undefined,
	nvObservacion: undefined,
	iIdEstado: undefined,
	dtCreacion: undefined,
	dtModificacion: undefined,
	vcUsuarioCreacionApp: undefined,
	vcUsuarioCreacionDB: undefined,
	vcUsuarioCreacionSP: undefined,
	vcUsuarioCreacionOT: undefined,
	vcUsuarioModificacionApp: undefined,
	vcUsuarioModificacionDB: undefined,
	vcUsuarioModificacionSP: undefined,
	vcUsuarioModificacionOT: undefined
}