/*model */
exports.Requerimiento = {
    iIdRequerimiento: undefined,
    vcNumeroDocumento: undefined,
    vcIdSedeOrigen: undefined,
    iIdUnidadOrganizativa: undefined,
    vcIdSede: undefined,
    vcRucEmpresa: undefined,
    vcCodigoUbigeo: undefined,
    dtFecha: undefined,
    nvObservacion:  undefined,
    vcAdjunto: undefined,
    iIdEstadoAprobacion: undefined,
    iIdEstadoConfirmacion: undefined,
    iIdEstado: undefined,
    dtCreacion: undefined,
    dtModificacion: undefined,
    vcUsuarioCreacionApp: undefined,
    vcUsuarioCreacionDB: undefined,
    vcUsuarioCreacionSP: undefined,
    vcUsuarioCreacionOT: undefined,
    vcUsuarioModificacionApp: undefined,
    vcUsuarioModificacionDB: undefined,
    vcUsuarioModificacionSP: undefined,
    vcUsuarioModificacionOT: undefined
}